services:
  rotation:
    develop:
      watch:
        - action: rebuild
          path: ./server
          ignore:
            - node_modules/
            - dist/
            - data/
        - action: rebuild
          path: ./web
          ignore:
            - node_modules/
            - dist/
